title:              Kamil Górny
email:              kamil.gorny99@gmail.com
description:        Blog about cybersecurity and programming
author:             Kamil Górny
baseurl:            "/"
url:                "https://kamil-gorny.github.io/"

# Social Profiles
twitter_username:   kamil_gorny99
github_username:    kamil-gorny
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-171679956-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
